version: "3.8"

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../config/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/frontend
    networks:
      - strapi
  backend:
    build:
      context: ../backend
      dockerfile: ../config/Dockerfile.backend
    ports:
      - "1337:1337"
    volumes:
      - ../backend:/backend
    environment:
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_SSL: ${DATABASE_SSL}
      NODE_ENV: development
    networks:
      - strapi
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - strapi

networks:
  strapi:
volumes:
  db: