version: "3.8"

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../config/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/frontend
    networks:
      - strapi
  backend:
    build:
      context: ../backend
      dockerfile: ../config/Dockerfile.backend
    ports:
      - "1337:1337"
    volumes:
      - ../backend:/backend
    networks:
      - strapi

networks:
  strapi: